name: CI

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download bore
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "https://github.com/ekzhang/bore/releases/download/v0.6.0/bore-v0.6.0-x86_64-pc-windows-msvc.zip" `
            -OutFile "bore.zip"

          Expand-Archive bore.zip -DestinationPath .
          Remove-Item bore.zip

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name "fDenyTSConnections" `
            -Value 0

          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name "UserAuthentication" `
            -Value 1

      - name: Create User
        shell: powershell
        run: |
          net user rdpuser Password123! /add
          net localgroup "Remote Desktop Users" rdpuser /add

      - name: Start bore
        shell: powershell
        run: |
          Start-Process `
            -FilePath ".\bore.exe" `
            -ArgumentList "local 3389 --to bore.pub" `
            -RedirectStandardOutput "bore.txt" `
            -NoNewWindow

          Start-Sleep -Seconds 10

          $content = Get-Content bore.txt -Raw

          if ($content -match "bore.pub:(\d+)") {
              $port = $matches[1]

              Write-Host ""
              Write-Host "==========================="
              Write-Host "RDP LOGIN INFO"
              Write-Host "==========================="
              Write-Host "HOST: bore.pub"
              Write-Host "PORT: $port"
              Write-Host "USER: rdpuser"
              Write-Host "PASS: Password123!"
              Write-Host "==========================="
          }
          else {
              Write-Host "Tunnel failed"
              Get-Content bore.txt
              exit 1
          }

      - name: Keep Alive
        shell: powershell
        run: |
          while ($true) {
            Start-Sleep -Seconds 60
            Write-Host "Alive $(Get-Date)"
          }
